# Generated by Django 6.0.4 on 2026-05-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_image_product_supabase_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
    ]
