# Generated by Django 6.0.4 on 2026-05-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_country_sellerprofile_payment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='📦', help_text='Emoji icon', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='State/Province/Region name', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code (e.g., GA for Greater Accra)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='store.country')),
            ],
            options={
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
