# Generated by Django 6.0.4 on 2026-05-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_userprofile_country_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text="User's country for phone formatting & currency", null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.country'),
        ),
    ]
