# Generated by Django 6.0.4 on 2026-05-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='Profile picture URL (Supabase or local)', null=True),
        ),
    ]
