# Generated by Django 6.0.4 on 2026-05-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cart_user_cartitem_added_at_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Country of residence', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
