# Generated by Django 6.0.2 on 2026-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_review_options_remove_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vr_supabase_path',
            field=models.CharField(blank=True, help_text='Supabase storage path for the VR file (GLB or 360 image)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vr_type',
            field=models.CharField(blank=True, choices=[('3d_model', '3D Model'), ('360_image', '360 Image')], max_length=20, null=True),
        ),
    ]
