# Generated by Django 6.0.2 on 2026-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_sellerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, help_text='Selected size for this item', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_size',
            field=models.BooleanField(default=False, help_text='Check if product has size options (e.g., shoes, clothing)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_stock',
            field=models.JSONField(blank=True, default=dict, help_text="JSON mapping of size to quantity. Example: {'S': 10, 'M': 5}"),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Global stock count (used if size is not required)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vr_supabase_path',
            field=models.CharField(blank=True, help_text='Supabase storage path for the VR file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='e.g., 1 Year Manufacturer Warranty', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Short code', max_length=10),
        ),
    ]
