# Generated by Django 6.0.4 on 2026-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_orderitem_size_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='vr_supabase_path',
            field=models.CharField(blank=True, help_text='Supabase storage path for the VR file (GLB or 360 image)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Short code (e.g., GA for Greater Accra)', max_length=10),
        ),
    ]
