# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_cart_members_cartitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wearable',
            field=models.BooleanField(default=False, help_text='Check if this product is wearable (e.g., shirt, shoe) so buyers can pick a size'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes for wearable items, e.g. S, M, L, XL or 39, 40, 41', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm (for non-wearable items, e.g. a box)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm (for non-wearable items, e.g. a box)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm (for non-wearable items, e.g. a box)', max_digits=8, null=True),
        ),
    ]
