# Generated by Django 6.0.4 on 2026-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='supabase_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
