# Generated by Django 6.0.4 on 2026-05-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_reference_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter your WhatsApp number with country code (e.g., +233241234567)', max_length=20),
        ),
    ]
