# Generated by Django 6.0.4 on 2026-05-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20260506_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-3 code', max_length=3, unique=True)),
                ('phone_code', models.CharField(help_text='e.g., +233 for Ghana', max_length=5)),
                ('currency', models.CharField(default='GHS', help_text='ISO 4217 currency code', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='payment_number',
            field=models.CharField(blank=True, help_text='Mobile money or bank-linked number for receiving payments', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='region',
            field=models.CharField(blank=True, help_text='State/Region/Province for delivery & tax calculations', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon (auto-filled)', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('smartphones', '📱 Smartphones'), ('laptops', '💻 Laptops & Computers'), ('tablets', '📟 Tablets'), ('audio', '🎧 Audio & Headphones'), ('cameras', '📷 Cameras & Photography'), ('accessories', '🔌 Tech Accessories'), ('gaming', '🎮 Gaming'), ('mens-fashion', "👔 Men's Fashion"), ('womens-fashion', "👗 Women's Fashion"), ('kids-fashion', "🧒 Kids' Fashion"), ('shoes', '👟 Shoes & Sneakers'), ('bags', '👜 Bags & Luggage'), ('watches', '⌚ Watches'), ('beauty', '💄 Beauty & Cosmetics'), ('fragrance', '🌸 Fragrances'), ('furniture', '🪑 Furniture'), ('home-decor', '🏠 Home Decor'), ('kitchen', '🍳 Kitchen & Dining'), ('bedding', '🛏️ Bedding & Bath'), ('appliances', '🔌 Home Appliances'), ('gardening', '🌱 Gardening'), ('health', '💊 Health & Wellness'), ('personal-care', '🧴 Personal Care'), ('baby-care', '🍼 Baby & Toddler'), ('sports', '⚽ Sports & Fitness'), ('outdoor', '🏕️ Outdoor & Camping'), ('cycling', '🚴 Cycling'), ('automotive', '🚗 Automotive'), ('tools', '🔧 Tools & Hardware'), ('electrical', '⚡ Electrical & Lighting'), ('books', '📚 Books & Literature'), ('music', '🎵 Music & Instruments'), ('movies', '🎬 Movies & TV'), ('food', '🍎 Food & Beverages'), ('groceries', '🛒 Groceries'), ('toys', '🧸 Toys & Games'), ('pet-supplies', '🐾 Pet Supplies'), ('office', '🖊️ Office Supplies'), ('crafts', '🎨 Arts & Crafts')], max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text="User's country for phone formatting & currency", null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.country'),
        ),
    ]
