# Generated by Django 6.0.4 on 2026-05-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_userprofile_avatar_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Comma-separated: Red, Blue, Black', max_length=200),
        ),
    ]
