# Generated by Django 6.0.2 on 2026-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_vr_supabase_path_product_vr_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Seller Profiles'},
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal admin notes (not visible to seller)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rejected_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (visible to seller)'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when admin approved', null=True),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, default='#')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='store_admin_is_read_6a5ac1_idx')],
            },
        ),
    ]
