# Generated by Django 6.0.4 on 2026-09-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_is_wearable_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
