# Generated by Django 6.0.4 on 2026-09-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_shared_cart_payment_notifications'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='store_usern_user_id_90270f_idx',
            old_name='store_userno_user_id_9e8e5b_idx',
        ),
    ]
